- name: Obtener vecinos LLDP
  hosts: all
  gather_facts: no
  tasks:
    - name: Ejecutar show lldp neighbors
      ansible.netcommon.cli_command:
        command: show lldp neighbors | json
      register: lldp_info

    - name: mostrar resultados
      debug:
        var: lldp_info.json

    - name: Guardar resultado
      copy:
        content: "{{ lldp_info.stdout }}"
        dest: "./{{ inventory_hostname }}_lldp.txt"
      delegate_to: localhost
