- name: Obtener y parsear LLDP neighbors
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Ejecutar comando y parsear con ios_command + TextFSM
      cisco.ios.ios_command:
        commands:
          - show lldp neighbors detail
        use_textfsm: yes
      register: lldp_output

    - name: Mostrar resultado parseado
      debug:
        var: lldp_output.stdout[0]
