---
- name: Procesar LLDP info simple
  hosts: localhost
  gather_facts: no

  vars:
    lldp_lines:
      - "lab-bel-n5672-02     Eth1/1          120        B           Eth1/1            "
      - "lab-bel-n5672-02     Eth1/3          120        B           Eth1/3            "
      - "lab-bel-n5k.lab.local Eth1/11         120        B           Eth1/11           "
      - "UCS-LAB-FI-A         Eth1/19         120        B           Eth1/19           "
      - "UCS-LAB-FI-B         Eth1/20         120        B           Eth1/19           "
      - "lab-bsas-leaf101     Eth1/25         120        BR          Eth1/47           "

  tasks:

    - name: Parsear líneas y armar lista de diccionarios
      set_fact:
        lldp_parsed: >-
          {{
            lldp_lines
            | map('regex_replace', '\\s+', ' ')    # Normalizo espacios a uno solo
            | map('trim')
            | map('split', ' ')
            | map('list')
            | map('community.general.dict_kv', ['device_id', 'port_id', 'hold_time', 'flags', 'port_id2'])
            | list
          }}

    - name: Mostrar resultado
      debug:
        var: lldp_parsed
