- name: Obtener y parsear LLDP neighbors sin Python
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Ejecutar comando show lldp neighbors detail
      cisco.ios.ios_command:
        commands:
          - show lldp neighbors detail
      register: lldp_output

    - name: Extraer nombres de vecinos LLDP
      set_fact:
        lldp_neighbors: "{{ lldp_output.stdout[0] | regex_findall('Device ID: ([^\\n]+)') }}"

    - name: Mostrar vecinos extraidos
      debug:
        var: lldp_neighbors
