- name: Obtener y parsear LLDP neighbors
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Ejecutar comando con ios_command (sin parseo)
      cisco.ios.ios_command:
        commands:
          - show lldp neighbors detail
      register: raw_output

    - name: Parsear salida con cli_parse y TextFSM
      ansible.netcommon.cli_parse:
        platform: cisco.ios
        command: show lldp neighbors detail
        output: "{{ raw_output.stdout[0] }}"
      register: parsed_output

    - name: Mostrar salida parseada
      debug:
        var: parsed_output.parsed
