---
- name: Procesar LLDP info con formato de columnas y espacios
  hosts: localhost
  gather_facts: no

  vars:
    lldp_lines:
      - "lab-bel-n5672-02     Eth1/1          120        B           Eth1/1            "
      - "lab-bel-n5672-02     Eth1/3          120        B           Eth1/3            "
      - "lab-bel-n5k.lab.local Eth1/11         120        B           Eth1/11           "
      - "UCS-LAB-FI-A         Eth1/19         120        B           Eth1/19           "
      - "UCS-LAB-FI-B         Eth1/20         120        B           Eth1/19           "
      - "lab-bsas-leaf101     Eth1/25         120        BR          Eth1/47           "

  tasks:

    - name: Extraer device_id, hold_time y port_id con regex
      set_fact:
        lldp_data: >-
          {{
            lldp_lines
            | map('regex_search', '^(\\S+)\\s+(\\S+)\\s+(\\d+)\\s+\\S+\\s+(\\S+)', '\\1,\\3,\\4')
            | list
          }}

    - name: Convertir las cadenas extraídas a diccionarios
      set_fact:
        lldp_json: >-
          {{
            lldp_data
            | map('split', ',')
            | map('zip', ['device_id', 'hold_time', 'port_id'])
            | map('items2dict')
            | list
          }}

    - name: Mostrar resultado final
      debug:
        var: lldp_json
