---
- name: Extraer y procesar LLDP info
  hosts: all
  gather_facts: no

  vars:
    lldp_output: |
      lab-bel-n5672-02 120 Eth1/1
      lab-bel-n5672-02 120 Eth1/3

  tasks:
    - name: Extraer device_id, hold_time y port_id con regex_findall
      set_fact:
        raw_matches: "{{ lldp_output | regex_findall('([\\w\\-]+)\\s+(\\d+)\\s+(Eth[\\w/]+)') }}"

    - name: Filtrar solo coincidencias no vacías (descartar listas vacías)
      set_fact:
        filtered: "{{ raw_matches | select('length') | list }}"

    - name: Construir lista de diccionarios con device_id, hold_time y port_id
      set_fact:
        lldp_json: >-
          {{
            filtered
            | map('zip', ['device_id', 'hold_time', 'port_id'])
            | map('map', 'reverse')
            | map('map', 'list')
            | map('items2dict')
            | list
          }}

    - name: Mostrar resultado final
      debug:
        var: lldp_json
