---
- name: Obtener y parsear LLDP neighbors
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - ansible.netcommon

  tasks:
    
    - name: Ejecutar comando y parsear con cli_command + TextFSM
      ansible.netcommon.cli_command:
        command: show lldp neighbors detail
        use_textfsm: yes
      register: parsed_output

    - name: Mostrar resultado parseado
      debug:
        var: parsed_lldp.parsed
