- name: Obtener LLDP neighbors sin parseo
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Ejecutar comando show lldp neighbors detail
      cisco.ios.ios_command:
        commands:
          - show lldp neighbors
      register: raw_output

    - name: Mostrar salida cruda
      debug:
        var: raw_output.stdout[0]
