---
- name: Procesar LLDP info simple
  hosts: localhost
  gather_facts: no

  vars:
    lldp_lines:
      - "lab-bel-n5672-02     Eth1/1          120        B           Eth1/1            "
      - "lab-bel-n5672-02     Eth1/3          120        B           Eth1/3            "
      - "lab-bel-n5k.lab.local Eth1/11         120        B           Eth1/11           "
      - "UCS-LAB-FI-A         Eth1/19         120        B           Eth1/19           "
      - "UCS-LAB-FI-B         Eth1/20         120        B           Eth1/19           "
      - "lab-bsas-leaf101     Eth1/25         120        BR          Eth1/47           "

  tasks:
    - name: Normalizar espacios y split
      set_fact:
        parsed_list: "{{ parsed_list | default([]) + [ item | regex_replace('\\s+', ' ') | trim | split(' ') ] }}"
      loop: "{{ lldp_lines }}"

    - name: Mostrar parsed_list
      debug:
        var: parsed_list

    - name: Extraer solo los 3 primeros elementos de cada sublista
      set_fact:
        shortened_list: "{{ parsed_list | map('slice', 0, 3) | list }}"

    - name: Armar lista de diccionarios con campos device_id, port_id y hold_time
      set_fact:
        lldp_dicts: >-
          {{
            shortened_list
            | map('zip', ['device_id', 'port_id', 'hold_time'])
            | map('items2dict')
            | list
          }}

    - name: Mostrar lista final de diccionarios
      debug:
        var: lldp_dicts
