---
- name: Obtener y parsear LLDP neighbors
  hosts: all
  gather_facts: no
  connection: network_cli
  collections:
    - ansible.netcommon

  tasks:
    - name: Ejecutar comando LLDP
      cisco.ios.ios_command:
        commands:
          - show lldp neighbors
      register: lldp_output

    - name: Parsear salida con TextFSM (usando cli_parse)
      ansible.netcommon.cli_parse:
        command: show lldp neighbors
        output: "{{ lldp_output.stdout[0] }}"
        parser:
          name: ansible.netcommon.textfsm
      register: parsed_lldp

    - name: Mostrar resultado parseado
      debug:
        var: parsed_lldp.parsed
