- name: Obtener y parsear LLDP neighbors sin Python
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Ejecutar comando show lldp neighbors detail
      cisco.ios.ios_command:
        commands:
          - show lldp neighbors
      register: lldp_output

    - name: Mostrar vecinos extraidos
      debug:
        var: lldp_output

    - name: Extraer nombres de vecinos LLDP
      set_fact:
         lldp_lines: "{{ lldp_output.stdout_lines[0][4:-1] }}"

    - name: Construir lista de diccionarios con campos Device ID, Hold-time y Port ID
      set_fact:
        lldp_json: >-
          {{
            lldp_lines.stdout_lines[0] | 
            map('regex_search', '^(\\S+)\\s+\\S+\\s+(\\d+)\\s+\\S+\\s+(\\S+)') | 
            map('list') |
            map('zip', ['device_id', 'hold_time', 'port_id']) |
            map('items2dict') | list
          }}

    - name: Mostrar JSON construido
      debug:
        var: lldp_json
