---
- name: Procesar salida LLDP
  hosts: all
  gather_facts: false
  vars:
    lldp_lines:
      - "lab-bel-n5672-02     Eth1/1          120        B           Eth1/1            "
      - "lab-bel-n5672-02     Eth1/3          120        B           Eth1/3            "
      - "lab-bel-n5k.lab.localEth1/11         120        B           Eth1/11           "
      - "UCS-LAB-FI-A         Eth1/19         120        B           Eth1/19           "
      - "UCS-LAB-FI-B         Eth1/20         120        B           Eth1/19           "
      - "lab-bsas-leaf101     Eth1/25         120        BR          Eth1/47           "

  tasks:
    - name: Mostrar lldp_lines
      debug:
        var: lldp_lines

    - name: Aplicar regex_findall para extraer Device ID, Hold-time y Port ID
      set_fact:
        raw_matches: "{{ lldp_lines | map('regex_findall', '^(\\S+)\\s+\\S+\\s+(\\d+)\\s+\\S+\\s+(\\S+)') | list }}"

    - name: Mostrar raw_matches
      debug:
        var: raw_matches

    - name: Filtrar solo coincidencias no vacías
      set_fact:
        filtered: "{{ raw_matches | select(lambda x: x | length > 0) | list }}"

    - name: Mostrar filtered
      debug:
        var: filtered

    - name: Construir lista de diccionarios con device_id, hold_time y port_id
      set_fact:
        lldp_json: "{{ filtered | map('first') | map('zip', ['device_id', 'hold_time', 'port_id']) | map('items2dict') | list }}"

    - name: Mostrar JSON final
      debug:
        var: lldp_json
